name: tv_series
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  cupertino_icons: null
  dio: null
  flutter:
    sdk: flutter
  flutter_bloc: ^7.2.0
  freezed_annotation: null
  html: ^0.15.0
  infinite_scroll_pagination: ^3.1.0
  transparent_image: ^2.0.0

dev_dependencies:
  build_runner: null
  flutter_test:
    sdk: flutter
  freezed: null
  json_serializable: null
  lint: null

flutter:
  uses-material-design: true
  #assets:
  #- assets/
